---

- name: "Install nginx"
  when: ansible_os_family == 'Debian'
  apt:
    name=nginx
    state=present

- name: "Start nginx and set systemd to start it on boot"
  systemd:
    name: nginx
    state: started
    enabled: yes
